### ISSUE TITLE
[Bug?]:  Dev server crashes when there is a syntax error

### ISSUE THREAD

**Issue by doeixd** [solidjs/solid-start#1222]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

I have auto save enabled on my editor, and when I'm editing the code, there will be a temporary state where there is a syntax error, during this time the solid start / vinxi dev server crashes, and has to be restarted. This slows down development.

Here is the error: 

```
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Transform failed with 1 error:
<stdin>:15:41: ERROR: Expected ";" but found ")"
    at failureErrorWithLog (C:\Users\Pglenn\Desktop\convert\Final\interface\node_modules\esbuild\lib\main.js:1649:15)
    at C:\Users\Pglenn\Desktop\convert\Final\interface\node_modules\esbuild\lib\main.js:847:29
    at responseCallbacks.<computed> (C:\Users\Pglenn\Desktop\convert\Final\interface\node_modules\esbuild\lib\main.js:703:9)
    at handleIncomingPacket (C:\Users\Pglenn\Desktop\convert\Final\interface\node_modules\esbuild\lib\main.js:762:9)
    at Socket.readFromStdout (C:\Users\Pglenn\Desktop\convert\Final\interface\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:519:28)
    at addChunk (node:internal/streams/readable:559:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
    at Readable.push (node:internal/streams/readable:390:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 41,
        file: '<stdin>',
        length: 1,
        line: 15,
        lineText: '  let result =  await db.brand.findMany())',
        namespace: '',
        suggestion: ';'
      },
      notes: [],
      pluginName: '',
      text: 'Expected ";" but found ")"'
    }
  ],
  warnings: []
}
```

### Expected behavior 🤔

I would expect the dev server to print the error, then wait till the watcher sees a new version of the file, then use that updated file

### Steps to reproduce 🕹

Steps:

1. Create a syntax error
2.
3.
4.

### Your environment 🌎

```shell
Windows 11
```

**Comment by frenzzy** [comment]
+1, with latest solid-start version `0.4.3` example `with-auth` is not working anymore.

<img width="1550" alt="Screenshot 2024-01-05 at 20 21 35" src="https://github.com/solidjs/solid-start/assets/640669/514ef2f7-d1c9-44a5-9fa3-b0a6ebd3b21b">

By some reason import of `@solidjs/start/server` is compiled to `null`, for example:

```ts
import { useSession } from '@solidjs/start/server'

// TypeError: Cannot read properties of null (reading 'useSession')
```

**Comment by edivados** [comment]
> By some reason import of `@solidjs/start/server` is compiled to `null`, for example:
> 
> ```ts
> import { useSession } from '@solidjs/start/server'
> 
> // TypeError: Cannot read properties of null (reading 'useSession')
> ```

Importing `useSession` from `vinxi/server` instead seems to works. Only in dev. No idea why.
It's a re-re-export from h3.

**Comment by nksaraf** [comment]
> @frenzzy
> 
> > By some reason import of `@solidjs/start/server` is compiled to `null`, for example:
> > ```ts
> > import { useSession } from '@solidjs/start/server'
> > 
> > // TypeError: Cannot read properties of null (reading 'useSession')
> > ```
> 
> The problem is only in dev. Importing `useSession` from `vinxi/server` instead seems to work. No idea why. It's a re-re-export from h3.

should be fixed in latest version of solid start

**Comment by ryansolid** [comment]
with-auth issue is fixed now.

That being said @nksaraf if I go in any file and cause a JS syntx error, like mess up the closing tag of a JSX element the dev or missing a closing bracket on a function etc... server immediately crashes.

**Comment by angry-meow** [comment]
@nksaraf:

> should be fixed in latest version of solid start

FYI, in the latest version (`0.4.11`) it still crashes.

![image](https://github.com/solidjs/solid-start/assets/31481176/23defdc2-40a1-4c17-ac12-2a31e34d5c46)

It happens even with the JSX errors, e.g. `Invalid JSX: <tr> cannot be child of <table>`.

**Comment by doeixd** [comment]
I see this issue was closed on vinxi, but I am still experiencing this problem.

https://github.com/nksaraf/vinxi/issues/100

@nksaraf

**Comment by nksaraf** [comment]
can i get a precise repro. i have been trying to ssquash this issue and see it rarely myself now
