### ISSUE TITLE
[Bug?]: Auto generated URLs for file imports are inconsistent (between `/assets/...` and `/_build/assets/...`) leading to issue

### ISSUE THREAD

**Issue by elliotwaite** [solidjs/solid-start#1247]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Imported assets are output to two locations, `/assets/` and `/_build/assets/`. This lead to the following issue:

Note: All the code below can be found in [this demo repo](https://github.com/elliotwaite/solid-start-url-issue).

I have a font located at:
`/src/fonts/Poppins-Regular.ttf`

I used the font in the `app.css` file as the `src` for a `@font-face`.

`/src/app.css`:
```
@font-face {
  font-family: Poppins;
  font-weight: 400;
  src: url('./fonts/Poppins-Regular.ttf') format('ttf');
  font-display: swap;
}

h1 {
  font-family: Poppins;
}
```

And I imported the font in `entry-server.tsx` to list it as a preloaded asset (see the `PoppinsRegularURL` import below).

`/src/entry-server.tsx`:
```
import { createHandler } from '@solidjs/start/entry'
import { StartServer } from '@solidjs/start/server'
import PoppinsRegularURL from './fonts/Poppins-Regular.ttf'

export default createHandler(() => (
  <StartServer
    document={({ assets, children, scripts }) => (
      <html lang="en">
        <head>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link
            rel="preload"
            href={PoppinsRegularURL}
            as="font"
            type="font/ttf"
            crossorigin=""
          />
          {assets}
        </head>
        <body>
          <div id="app">{children}</div>
          {scripts}
        </body>
      </html>
    )}
  />
))
```

However, when I build and run the server, the CSS file uses the `/_build/assets/` URL:
`src:url(/_build/assets/Poppins-Regular-707fdc5c.ttf)`

And the preload tag uses the `/assets/` URL:
`<link rel="preload" href="/assets/Poppins-Regular-707fdc5c.ttf" as="font" type="font/ttf" crossorigin="">`

Which causes the preload not to work, and for the Chrome dev tools to display this warning in the console when the page is loaded:
> ```The resource http://localhost:3000/assets/Poppins-Regular-707fdc5c.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.```

Is this a bug or am I doing something wrong?

What is the heuristic that determines when `/assets/` or `/_build/assets/` is used?

If all asset filenames use a content hash, it seems like it might be better to just put all assets in `/assets/`. That would:
* Prevent potential duplicate content (the same file loaded from both `/assets/` or `/_build/assets/`).
* Prevent inconsistency edge cases like the one described above.
* Make it easier for developers to know where their assets will be output to.

Would there be any downsides to putting all the assets in `/assets/`?

### Expected behavior 🤔

I expected that importing the same file would produce the same URL string for both the CSS file and the JavaScript file.

### Steps to reproduce 🕹

Steps:

1. Clone [this demo repo](https://github.com/elliotwaite/solid-start-url-issue).
2.	Run `pnpm install`
3.	Run `pnpm dev` or `pnpm build && pnpm start`
4. Open the browser at `http://localhost:3000` and inspect the CSS and HTML source files to see the inconsistency.

### Context 🔦

I'm trying to import a font to use in CSS, and also preload that font from the index.html page.

### Your environment 🌎

```shell
OS: macOS Sonoma 14.1
Node: v18.18.0

@solidjs/start: 0.4.8
solid-js: 1.8.10
vinxi: 0.1.2
```

**Comment by nksaraf** [comment]
Yup I think this is a symptom of how we handle assets between server and client. So right now what happens is if some assets is loaded on the server it is available at assets/.. if it's imported by the client it's at /_build/assets

So when you are loading the asset via import in your entry server file it picks up the asset as a server asset, and adds the preload link for that.. but the asset you wanna preload is the client one.

Let me think over this for a day and see how we should fix these issues. I think putting things in the same folder is a decent idea but we might have to jump through a lot of hoops to manage the asset urls across the app. It might be better to give an easier way to preload the assets.

**Comment by elliotwaite** [comment]
Okay, sounds good. Thanks for the explanation.

**Comment by ryansolid** [comment]
@nksaraf did you conclude anything. Love to hear your thoughts.

**Comment by nksaraf** [comment]
Yeah so I was thinking about this problem. This is not a problem that's solved by two config options. Base path has significant meaning across the system. 

I think initially it is safe to assume that different routers can have have different assets and they be processed their own way and served at the base path of the server. 

For the ssr case, the server has a special link with the client router because the client hydrates the server output and needs to match. This kind of linking is not just evident in this assets problem. When bundling handlers separately let's say to deploy to different places, the ssr server needs to know about the clients manifest. 

So let's say I want to say that the ssr handler has a client link to the client router. Internal plugins can use this system to affect behaviour. For example in this case, our dev and build mode will use the linked client router's base as the ssr router's vite (mainly to server assets) base.

So both assets urls should map to /_build from now on.

Check the latest Vinxi version for this behaviour. Will also need a change in solid-start to actually establish the link between the two routers.

**Comment by elliotwaite** [comment]
@nksaraf the previous update is working great. It solved the issue related to using auto-generated hashed URLs for fonts. However, I noticed there is still an issue when using absolute paths for font URLs. And the issue only affects dev mode (`pnpm dev`), it works correctly in prod (`pnpm build && pnpm start`).

Here are the important parts of the setup (the full demo repo can be found [here](https://github.com/elliotwaite/solid-start-url-issue/tree/css-url-with-absolute-path)):

I have a font located at: `/public/fonts/Poppins-Regular.ttf`

And I point to that font in `/src/app.css`:
```
@font-face {
  font-family: Poppins;
  src: url('/fonts/Poppins-Regular.ttf') format('truetype');
}
...
```

And I preload that font in `/src/entry-server.tsx`:
```
...
<link
  rel="preload"
  href="/fonts/Poppins-Regular.ttf
  as="font"
  type="font/ttf"
  crossorigin=""
/>
...
```

When I run it in prod, the CSS file correctly uses the specified absolute path:
`src:url(/fonts/Poppins-Regular.ttf)`

However, in dev mode, it prepends `/_build` to the path:
`src:url(/_build/fonts/Poppins-Regular.ttf)`

Which makes it no longer match the preload path:
`<link rel="preload" href="/assets/Poppins-Regular.ttf" as="font" type="font/ttf" crossorigin="">`

... which causes the preload to no longer work and the following warning to be shown in the Chrome dev tools console:
> ```The resource http://localhost:3000/fonts/Poppins-Regular.ttf was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.```

My expectation for URLs in CSS files was that relative paths would be modified to point to their correct output location, but that absolute URLs would be left unmodified. But let me know if this expectation is incorrect.
