### ISSUE TITLE
[Bug?]: No route matched for preloading js assets

### ISSUE THREAD

**Issue by sotasan** [solidjs/solid-start#1422]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Hey, when I have `[[id]].tsx` as the index route, I get the warning `No route matched for preloading js assets`. I am using the file router.

### Expected behavior 🤔

The page works like excpected, but everytime I visit the route, the warning gets printed to the console.

### Steps to reproduce 🕹

Steps:

1. Create a new Project
2. Rename the `index.tsx` to `[[id]].tsx`

### Context 🔦

I am trying to rewrite my [pastebin](https://voidb.in), which is currently written in React + SSG, in Solid Start.

**Comment by tokitouq** [comment]
Hi @sotasan 
I'm getting same error even for index page without renaming.
Did you find any solution for this?

**Comment by birkskyum** [comment]
I see this as well. Wonder if it's the routes/api/auth/[...solidauth].ts that I have.

**Comment by ryansolid** [comment]
The question is why did it not match.. This means it won't add the proper preload headers. Is this specific to a certain syntax?  I admittedly haven't used `[[...something]]` in any examples yet so I will give it a shot.

**Comment by birkskyum** [comment]
I don't have this issue anymore.

**Comment by ryansolid** [comment]
Well the bug in the main post is real. Issue with the router. I have fixed it now in 0.13.2. I will update the templates.

**Comment by indeyets** [comment]
@ryansolid I still see this problem on my current app with latest solid-router and solid-start. should anything be done on my side to fix it?

**Comment by tonyrewin** [comment]
in my case it happens with the `context` **undefined** in `entry-server.tsx`:

```tsx
// @refresh reload
import { StartServer, createHandler } from '@solidjs/start/server'

export default createHandler(() => (
  <StartServer
    document={(context) => {
      if(!context) throw console.warn(context)
      
      ...
      
```

**Comment by alguadmar** [comment]
I had the same error and I just reloaded the server to solve it.

**Comment by gar1t** [comment]
I'm seeing this message reported on this basic router config:

```typescript
import { Route, Router } from "@solidjs/router";

export default function App() {
  return (
    <Router root={(props) => props.children}>
      <Route path="/" component={() => <>Hi</>} />
    </Router>
  );
}
```

I created a new project for this using the bare template and installing `@solidjs/router`. The repo that I used to show the warning is here:

https://github.com/gar1t/reproduce-solid-no-route-matched

Applicable versions:

```
  "dependencies": {
    "@solidjs/router": "^0.15.3",
    "@solidjs/start": "^1.0.11",
    "solid-js": "^1.9.2",
    "vinxi": "^0.4.3"
  },
```

**Comment by yurisich** [comment]
I am seeing a similar issue to what @gar1t reported.

If you create a solid start basic template, apply this diff and try and visit `https://localhost:3000/github/users/yurisich` and note the presence of a `data` in the console log for props. It does have a promise fetching to get the data, but it isn't rendering anything.

<details><summary>diff</summary>

```diff
commit d810ba143d351bda6f4dfdad62db5f2d88659a1c
Author: yurisich <andrew@yurisich.com>
Date:   Tue Feb 18 20:40:38 2025 -0500

    No route matched for preloading js assets.

diff --git a/demo/src/app.tsx b/demo/src/app.tsx
index d1359c8..7913e9f 100644
--- a/demo/src/app.tsx
+++ b/demo/src/app.tsx
@@ -1,9 +1,40 @@
 import { MetaProvider, Title } from "@solidjs/meta";
-import { Router } from "@solidjs/router";
+import { Router, Route, query, createAsync } from "@solidjs/router";
 import { FileRoutes } from "@solidjs/start/router";
-import { Suspense } from "solid-js";
+import { Suspense, Match } from "solid-js";
 import "./app.css";
 
+const getGithubUser = query(async name => {
+  const url = new URL(
+    `https://api.github.com/users/${name}`
+  );
+  const response = await fetch(url);
+  return await response.json();
+});
+
+const preloadGithubUser = ({ params, location, intent }) => {
+  return getGithubUser(params.name);
+};
+
+const GithubUser = props => {
+  const user = createAsync(() => getGithubUser(props.name));
+  console.log(props);
+  return (
+    <>
+      <Suspense fallback={<div>Loading...</div>}>
+        <Switch>
+          <Match when={user()}>
+            <h2>{user.login} has {user.public_repos} public repos.</h2>
+          </Match>
+          <Match when={user.error}>
+            <div>Error: {user.error.message}</div>
+          </Match>
+        </Switch>
+      </Suspense>
+    </>
+  );
+};
+
 export default function App() {
   return (
     <Router
@@ -17,6 +48,7 @@ export default function App() {
       )}
     >
       <FileRoutes />
+      <Route path="github/users/:name" component={GithubUser} preload={getGithubUser} />
     </Router>
   );
 }
```

</details>
