### ISSUE TITLE
[Bug?]: SolidStart 1.1.0 does not work with Bun

### ISSUE THREAD

**Issue by PalmDevs** [solidjs/solid-start#1800]
### Duplicates

- [x] I have searched the existing issues

### Latest version

- [x] I have tested the latest version

### Current behavior 😯

Using the `bare` template, the dev server starts, but going to the site causes server errors:

```
[vite] Internal server error: File URL path must be an absolute path
  Plugin: tanstack-start-directive-vite-plugin
  File: /@solid-refresh
      at fileURLToPath (native)
      at transform (C:\Users\Palm\Desktop\solid-project\node_modules\@tanstack\directive-functions-plugin\dist\esm\index.js:19:12)
      at <anonymous> (C:\Users\Palm\Desktop\solid-project\node_modules\vite\dist\node\chunks\dep-CfG9u7Cn.js:47598:19)
      at processTicksAndRejections (native) (x4)
```

### Expected behavior 🤔

Visiting the site should not cause any server errors.

### Steps to reproduce 🕹

Steps:

1. Create a new SolidStart project (I used the `bare` template with TypeScript)
2. `cd` into the directory and install dependencies
3. `bun --bun dev` ([why `--bun`?](https://bun.sh/docs/cli/run#bun)) 
4. Once the server starts, visit the site (eg. `localhost:3000`)
5. Notice the errors

### Context 🔦

I am trying to use SolidStart with Bun. It has worked great previously, but updating to 1.1.0 causes this issue.

### Your environment 🌎

```shell
System:
  OS: Microsoft Windows [Version 10.0.26100.3037]
  CPU: x86_64 (6 cores, 12 processors)
Binaries:
  Bun: 1.2.2
npmPackages:
  @solidjs/start@1.1.0
  solid-js@1.9.4
  vinxi@0.5.3
```

**Comment by phong-phuong** [comment]
Strange, I just tested creating a new project, and it works for me.

OS is alsoWindows, tested with older (1.1.x version of Bun) and latest version of bun (1.2.x).

**Comment by phong-phuong** [comment]
Try solidstart 1.1.1, just came out a day ago.
I know I had build issues with solidstart, 1.1.0, and that was fixed with 1.1.1.

**Comment by PalmDevs** [comment]
Nope, using SolidStart 1.1.1 didn't fix the issue. Did you start the dev server with `--bun`?

**Comment by PalmDevs** [comment]
![Project creation](https://github.com/user-attachments/assets/5f5feda3-016f-40cb-a21a-67a4cd1b5c1f)

![Dependency versions](https://github.com/user-attachments/assets/1b31cb02-1f6e-45f5-974a-4ae54d9fd092)

![Errors](https://github.com/user-attachments/assets/41a0d80a-8373-4900-87bd-8d533969c906)

**Comment by phong-phuong** [comment]
Ok I missed that important detail `bun --bun dev`, and didn't know that option existed, and is very useful.
When I use `bun --dev dev`, it does indeed fail with the same errors as yours.

**Comment by birkskyum** [comment]
I can't repro this, on macos.

**Comment by phong-phuong** [comment]
@birkskyum OS: Windows 11

**Comment by birkskyum** [comment]
@phong-phuong , and this works if you run npm dev instead, right?

**Comment by phong-phuong** [comment]
@birkskyum That is correct. Only the `bun --bun dev` command doesn't run successfully on Windows as described in this issue.

**Comment by birkskyum** [comment]
Okay. Then we need this ticket opened in bun repo instead, because it appear this is not an issue on our side, and bun has a mantra that "if it works in node it should work in bun."

**Comment by MarByteBeep** [comment]
Experiencing the same issue. Has this been forwarded to the Bun dev? If so, could someone reference the issue here?

**Comment by PalmDevs** [comment]
I think Jarred had seen me posting about this issue in the SolidJS Discord server, but I haven't an issue on Bun's repository yet.

**Comment by MarByteBeep** [comment]
Would it be possible to create an issue? I think this one was slipped under the radar, since it's still a problem.
