### ISSUE TITLE
How to Fix Cannot read properties of null (reading 'nextSibling')

### ISSUE THREAD

**Issue by radensoft** [solidjs/solid-start#820]
I tried deploying apps to hosting but after running, an error occurred. provide solution for me with this problem. Thank you very much

Display ERROR

Cannot read properties of null (reading 'nextSibling')

TypeError: Cannot read properties of null (reading 'nextSibling')
    at https://serpihanruh.online/assets/index-171c9d48.js:1:4081
    at mt (https://serpihanruh.online/assets/index-171c9d48.js:1:4839)
    at https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:10982
    at Dt (https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:2921)
    at Object.fn (https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:10924)
    at Wr (https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:5563)
    at oi (https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:5345)
    at $n (https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:6707)
    at f1 (https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:7585)
    at Uh (https://serpihanruh.online/assets/entry-client-ac5326a7.js:1:6969)

**Comment by romanobro56** [comment]
if you want a quick fix, slap a <div> </div> at the bottom of your page. that should work for now

**Comment by ryansolid** [comment]
Try updating to the latest. These bugs have been fixed to my knowledge.

**Comment by radensoft** [comment]
thanks u

**Comment by radensoft** [comment]
Sorry, I've tried updating to the latest one, but the problem still persists

![Capture](https://user-images.githubusercontent.com/46371017/230970613-a6716871-d0b0-4134-bba2-431f383658b8.PNG)

**Comment by radensoft** [comment]
this is problematic when deploying to hosting, but if it's on VPS it's not a problem

**Comment by AlexErrant** [comment]
[Possibly related.](https://github.com/solidjs/solid-start/issues/823) Can you doublecheck your version numbers?

**Comment by eurmn** [comment]
Also happening with me (solid 1.7.4 + solid-start 0.2.26).
When accessing through localhost, it works great.
However, when accessing it through a domain (hosted in the same machine), it breaks.

**Comment by izcream** [comment]
Look like i got the same issues when try to access not localhost domian

solid-start: 0.2.26
solidjs: 1.7.5

<img width="375" alt="image" src="https://user-images.githubusercontent.com/10282500/236666589-a45763d5-a44e-4c5d-8fda-3c8cd1dd3d5a.png">

**Comment by Guergeiro** [comment]
Btw, this also happens with Astro. Just spent two days trying to debug this and I think I'm about to give up and just client render.

Seems like this person also has the problems: https://github.com/solidjs/solid/issues/1684#issuecomment-1518442395

**Comment by Guergeiro** [comment]
To add to this, it seems to work on static IPs, at least I deployed a docker container on my home server, and accessing via the server IP worked fine. As soon as I pointed a Cloudflare domain to it, it started getting the errors.

**Comment by jensmeindertsma** [comment]
Hey folks, I solved this issue by disabling Auto Minify for HTML in Cloudflare. This was removing comments used by Solid.

**Comment by Guergeiro** [comment]
Can confirm. Just switched Cloudflare minify off and it started working. Maybe @ryansolid can mention somewhere the docs that we should avoid any type of auto minifiers.
@radensoft does this solve your problem?

**Comment by ryansolid** [comment]
In setting up for SolidStarts next Beta Phase built on Nitro and Vinxi we are closing all PRs/Issues that will not be merged due to the system changing. If you feel your issue was closed by mistake. Feel free to re-open it after updating/testing against 0.4.x release. Thank you for your patience.  See https://github.com/solidjs/solid-start/pull/1139 for more details.
